spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: store-manager
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  front:
    url: ${FRONT_SOURCE:http://localhost:5173}
